common: &common
  database: nilify_blanks_test

sqlite3:
  adapter: sqlite3
  database: spec/db/test.sqlite3

postgresql:
  <<: *common
  adapter: postgresql

mysql:
  <<: *common
  adapter: mysql2
  username: root
